parameters:
- name: ShouldSkipOptimize
- name: OptProf
  type: boolean
  default: false

steps:
- task: notice@0
  displayName: 🛠️ Generate NOTICE file
  inputs:
    outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
    outputformat: text
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  retryCountOnTaskFailure: 3 # fails when the cloud service is overloaded

- task: MicroBuildOptProfPlugin@6
  inputs:
    ProfilingInputsDropName: ProfilingInputs/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
    OptimizationInputsLookupMethod: DropPrefix
    DropNamePrefix: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)
    ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
    AccessToken: $(System.AccessToken)
  displayName: 🔧 Install OptProf Plugin

# We have to install these plugins ourselves for Optprof runs because those pipelines haven't migrated to 1ES PT yet.
- ${{ if parameters.OptProf }}:
  - task: MicroBuildSigningPlugin@4
    inputs:
      signType: Real
      zipSources: false
    displayName: 🔧 Install MicroBuild Signing Plugin

  - task: MicroBuildLocalizationPlugin@3
    inputs:
      languages: $(LocLanguages)
    displayName: 🔧 Install MicroBuild Localization Plugin
